apiVersion: v1
kind: Service
metadata:
  name: ms-api-srv
spec:
  type: NodePort
  selector:
    app: ms-api
  ports:
    - name: ms-api
      protocol: TCP
      port: 8080 # port on the inside of our node (remember: this creates a port starting w/ 3####)
      targetPort: 8080 # port it should map to on our running app (inside a pod)